version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://localhost:27017/barber_finance

  frontend:
    build: ./frontend
    ports:
      - '4200:4200'

volumes:
  mongo-data:
